### ISSUE TITLE
I cannot get it running

### ISSUE THREAD

**Issue by tsadak** [harmon25/node-usb-barcode-scanner#11]
Hello

//initialize new usbScanner - takes optional parmeters vendorId and hidMap - check source for details 
var scanner = new usbScanner();

I couldn't find how to run this line, that is how to supply the optional parameters to find my scanner and use it in the source! and how i find hidMap?

Please help

**Comment by tsadak** [comment]
OK i found it.
But there is another problem. Can we open the device using its path? because we are going to use many same barcode scanners connected to the same raspberry. in that case vid and pid are all same, so we have to diffenretiate between different scanners by their paths?

**Comment by harmon25** [comment]
merged changes to master which allow initialising a device via its path rather than vendorId
