### ISSUE TITLE
Question: is it supported on Windows?

### ISSUE THREAD

**Issue by lafar6502** [harmon25/node-usb-barcode-scanner#15]
Hi, i have a problem installing the lib on Windows
is it supported at all, or just linux?
if supported
- what are the dependencies? The package.json file says it's just node-hid, which installs without any problems. But npm install node-usb-barcode-scanner fails with some complaints about Python missing.
So - is Python required as well? What else?

thanks
RG

**Comment by harmon25** [comment]
In looking closer at the node-hid readme.
https://github.com/node-hid/node-hid#windows-notes

> ### Mice and keyboards
> In general you cannot access USB HID keyboards or mice.
> The OS owns these devices.


Which is likely the problem, the USB barcode scanner this was designed for presents itself as a Keyboard in linux/mac.

I will add a note that this library does not support Windows, sorry!
