### ISSUE TITLE
Detect shift command

### ISSUE THREAD

**Issue by demobiel** [harmon25/node-usb-barcode-scanner#16]
Hi

thanks for your library, as we have barcodes with both lower as uppercase, I just wanted to say: in the chunk[0] you can detect if it is a SHIFT press or not.

```
if(chunk[0] === 2 )
    key = "shift_" + chunk[2]
} else {
    key = chunk[2]
}
```

and by passing a HID map that differentiates between them it works :)

**Comment by harmon25** [comment]
Glad it works for you!
The HID map as a config was to help with these kinds of issues.

Closing.
