### ISSUE TITLE
Vendors hidMap

### ISSUE THREAD

**Issue by mariowise** [harmon25/node-usb-barcode-scanner#2]
Hello, I wonder where did you find the vendors hidMap? I mean, where does this come from?

```
this.hidMap = options.hidMap || {
4:"A", 5:"B",6:"C",7:"D",8:"E",
9:"F", 10:"G", 11:"H",12:"I",13:"J",
14:"K",15:"L",16:"M",17:"N", 18:"O",
19:"P",20:"Q",21:"R",22:"S",23:"T",
24:"U",25:"V", 26:"W", 27:"X", 28:"Y",
29:"Z",30: '1', 31: '2', 32: '3', 33: '4',
34: '5',35: '6', 36: '7', 37: '8', 38: '9',
// enter - barcode escape char
39: '0',40: 'enter', 44:" ",45:"-", 55:".", 56:"/",
85:"*", 87:"+"
};
```

**Comment by harmon25** [comment]
Pretty sure I used [this as reference](http://www.freebsddiary.org/APC/usb_hid_usages.php), specifically the Keyboard section.

I only added the mappings which i thought were necessary, it might need some adjustments.
