### ISSUE TITLE
Hardcoded escape hidMap

### ISSUE THREAD

**Issue by NMathar** [harmon25/node-usb-barcode-scanner#5]
Hi,

is it possible to add the escape hidMap id (40)

``` javascript
 if (chunk[2] !== 40) {
            bcodeBuff.push(hidMap[chunk[2]])
 }
```

to the configuartion object and give it a default value? 

My device has the escape id on 49 and i have to edit your code to fix that right? 

Greetings,

NMonst4

**Comment by harmon25** [comment]
accepting your pull request, good idea!

sorry this took so long!
