### ISSUE TITLE
close function

### ISSUE THREAD

**Issue by SteampunkProfessor** [harmon25/node-usb-barcode-scanner#6]
Brilliant work so far! 
Any chance of adding a close function?

**Comment by harmon25** [comment]
This can be done, using [node-hid](https://github.com/node-hid/node-hid) under the hood - just need to create a method for it.

**Comment by harmon25** [comment]
Just merged a pull request by @oskaryil  that adds a `stopScanning` method to close the hid device.

**Comment by SteampunkProfessor** [comment]
Thanks for the email, I'll be updating the code on my Pi soon. 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Doug <notifications@github.com> Date: 21/05/2017  4:47 p.m.  (GMT+00:00) To: harmon25/node-usb-barcode-scanner <node-usb-barcode-scanner@noreply.github.com> Cc: SteampunkProfessor <steampunkprofessor@gmail.com>, Author <author@noreply.github.com> Subject: Re: [harmon25/node-usb-barcode-scanner] close function (#6) 
Closed #6.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/harmon25/node-usb-barcode-scanner","title":"harmon25/node-usb-barcode-scanner","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/harmon25/node-usb-barcode-scanner"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #6."}],"action":{"name":"View Issue","url":"https://github.com/harmon25/node-usb-barcode-scanner/issues/6#event-1090874621"}}}
