### ISSUE TITLE
Uncaught Error: cannot open device with path

### ISSUE THREAD

**Issue by vincentracine** [harmon25/node-usb-barcode-scanner#8]
USB Barcode Scanner which emulates a keyboard on Mac OS. I get the following error:
`Uncaught Error: cannot open device with path USB_0e6a_0305_14100000z`

**Comment by ChaimF90** [comment]
I got the same error using my iphone as the scanner. The iphone was recognized as a device tho.

**Comment by harmon25** [comment]
@vincentracine - i could test on Mac, did you figure it out?  may just need to pass the correct device path or something....

@ChaimF90  unlikely this would work with an iPhone app...

**Comment by stevanmilic** [comment]
Try `sudo`

**Comment by jitendra-khatri** [comment]
@stevanmilic Is there any to get this work on Windows Machine. On Ubuntu machine it is working fine with `sudo`.

**Comment by coryhake** [comment]
@jitendra-khatri have you tried to use "Run as Administrator" when opening your command prompt/shell?

**Comment by ghost** [comment]
I had the same issue and tried passing a defined vendorId for a honeywell scanner, it got a little further but now I get: 

`cannot open device with path \\?\hid#vid_0c2e&pid_0200#7&2dc7e600&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}`
`at new HID (c:\Dev\test-scanner\node_modules\node-hid\index.js:24:14)`

I am running this in an elevated command prompt.

**Comment by jitendra-khatri** [comment]
@coryhake I have build for windows and tried to run the APP_NAME.exe file with option "Run As Administrator". But, unfortunately no luck.

**Comment by ghost** [comment]
did someone make it work in Windows ?

**Comment by harmon25** [comment]
see #15
